In [210]:
import pandas as pd
import numpy as np

In [211]:
pd.set_option('display.max_columns', 500)

In [212]:
df=pd.read_csv('marketing_sample_for_naukri_com-jobs__20190701_20190830__30k_data.csv')
df.head()

Uniq Id            Crawl Timestamp  \
0  9be62c49a0b7ebe982a4af1edaa7bc5f  2019-07-05 01:46:07 +0000   
1  3c52d436e39f596b22519da2612f6a56  2019-07-06 08:04:50 +0000   
2  ffad8a2396c60be2bf6d0e2ff47c58d4  2019-08-05 15:50:44 +0000   
3  7b921f51b5c2fb862b4a5f7a54c37f75  2019-08-05 15:31:56 +0000   
4  2d8b7d44e138a54d5dc841163138de50  2019-07-05 02:48:29 +0000   

                                           Job Title  \
0                              Digital Media Planner   
1                           Online Bidding Executive   
2   Trainee Research/ Research Executive- Hi- Tec...   
3                                  Technical Support   
4                  Software Test Engineer -hyderabad   

                     Job Salary Job Experience Required  \
0   Not Disclosed by Recruiter               5 - 10 yrs   
1   Not Disclosed by Recruiter                2 - 5 yrs   
2   Not Disclosed by Recruiter                0 - 1 yrs   
3      2,00,000 - 4,00,000 PA.                0 - 5 yrs   
4   Not Disclosed by Recruiter                2 - 5 yrs   

                                          Key Skills  \
0                      Media Planning| Digital Media   
1   pre sales| closing| software knowledge| clien...   
2   Computer science| Fabrication| Quality check|...   
3                                  Technical Support   
4   manual testing| test engineering| test cases|...   

                                Role Category   Location  \
0                                 Advertising     Mumbai   
1                                Retail Sales  Pune,Pune   
2                                         R&D    Gurgaon   
3  Admin/Maintenance/Security/Datawarehousing     Mumbai   
4                        Programming & Design  Hyderabad   

                                     Functional Area  \
0  Marketing , Advertising , MR , PR , Media Plan...   
1              Sales , Retail , Business Development   
2                           Engineering Design , R&D   
3  IT Software - Application Programming , Mainte...   
4                         IT Software - QA & Testing   

                                Industry                              Role  
0  Advertising, PR, MR, Event Management  Media Planning Executive/Manager  
1         IT-Software, Software Services           Sales Executive/Officer  
2                  Recruitment, Staffing                     R&D Executive  
3         IT-Software, Software Services        Technical Support Engineer  
4         IT-Software, Software Services                  Testing Engineer

In [213]:
df['Job Title']=df['Job Title'].fillna('').map(lambda x:x.strip().lower())

In [214]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Job Title', 'Job Salary',
       'Job Experience Required', 'Key Skills', 'Role Category', 'Location',
       'Functional Area', 'Industry', 'Role'],
      dtype='object')

In [215]:
len(df['Job Title'].unique())

23230

In [216]:
df.shape

(30000, 11)

In [217]:
df.isnull().sum()

Uniq Id                       0
Crawl Timestamp               0
Job Title                     0
Job Salary                   50
Job Experience Required     573
Key Skills                 1271
Role Category              2305
Location                    577
Functional Area             573
Industry                    573
Role                        901
dtype: int64

In [218]:
df['Key Skills'].fillna('Not given',inplace=True)

In [219]:
df['Skill_1']=df['Key Skills'].map(lambda x:x.split('|')[0].lower().strip() if x!='Not given' else "Not Given")

In [220]:
df['Skill_1']

0           media planning
1                pre sales
2         computer science
3        technical support
4           manual testing
               ...        
29995             graphics
29996     service delivery
29997            counselor
29998    security analysis
29999        press release
Name: Skill_1, Length: 30000, dtype: object

In [221]:
len(df['Skill_1'].unique())

5096

In [222]:
df['Skill_2']=df['Key Skills'].map(lambda x:x.split('|')[1].lower().strip() if x!='Not given' and len(x.split('|'))>1 else "Not Given")

In [223]:
len(df['Skill_2'].unique())

5378

In [224]:
df['Skill_3']=df['Key Skills'].map(lambda x:x.split('|')[2].lower().strip() if x!='Not given' and len(x.split('|'))>2 else "Not Given")

In [225]:
df.head()

Uniq Id            Crawl Timestamp  \
0  9be62c49a0b7ebe982a4af1edaa7bc5f  2019-07-05 01:46:07 +0000   
1  3c52d436e39f596b22519da2612f6a56  2019-07-06 08:04:50 +0000   
2  ffad8a2396c60be2bf6d0e2ff47c58d4  2019-08-05 15:50:44 +0000   
3  7b921f51b5c2fb862b4a5f7a54c37f75  2019-08-05 15:31:56 +0000   
4  2d8b7d44e138a54d5dc841163138de50  2019-07-05 02:48:29 +0000   

                                           Job Title  \
0                              digital media planner   
1                           online bidding executive   
2  trainee research/ research executive- hi- tech...   
3                                  technical support   
4                  software test engineer -hyderabad   

                     Job Salary Job Experience Required  \
0   Not Disclosed by Recruiter               5 - 10 yrs   
1   Not Disclosed by Recruiter                2 - 5 yrs   
2   Not Disclosed by Recruiter                0 - 1 yrs   
3      2,00,000 - 4,00,000 PA.                0 - 5 yrs   
4   Not Disclosed by Recruiter                2 - 5 yrs   

                                          Key Skills  \
0                      Media Planning| Digital Media   
1   pre sales| closing| software knowledge| clien...   
2   Computer science| Fabrication| Quality check|...   
3                                  Technical Support   
4   manual testing| test engineering| test cases|...   

                                Role Category   Location  \
0                                 Advertising     Mumbai   
1                                Retail Sales  Pune,Pune   
2                                         R&D    Gurgaon   
3  Admin/Maintenance/Security/Datawarehousing     Mumbai   
4                        Programming & Design  Hyderabad   

                                     Functional Area  \
0  Marketing , Advertising , MR , PR , Media Plan...   
1              Sales , Retail , Business Development   
2                           Engineering Design , R&D   
3  IT Software - Application Programming , Mainte...   
4                         IT Software - QA & Testing   

                                Industry                              Role  \
0  Advertising, PR, MR, Event Management  Media Planning Executive/Manager   
1         IT-Software, Software Services           Sales Executive/Officer   
2                  Recruitment, Staffing                     R&D Executive   
3         IT-Software, Software Services        Technical Support Engineer   
4         IT-Software, Software Services                  Testing Engineer   

             Skill_1           Skill_2             Skill_3  
0     media planning     digital media           Not Given  
1          pre sales           closing  software knowledge  
2   computer science       fabrication       quality check  
3  technical support         Not Given           Not Given  
4     manual testing  test engineering          test cases

In [226]:
df['Role Category'].fillna('Not Given',inplace=True)

In [227]:
df['Role Category']=df['Role Category'].map(lambda x:x.split('/')[0].lower().strip() if '/' in x else x.lower())

In [228]:
role_dict=df['Role Category'].value_counts().to_dict()

In [229]:
final_role_dict={k:i for k,i in role_dict.items() if i>=6}

In [230]:
roles_keys=final_role_dict.keys()


In [231]:
df['Role Category']=df['Role Category'].map(lambda x:x if x in roles_keys else "Other")

In [232]:
df['Role Category'].value_counts().to_dict()

{'programming & design': 8551,
 'voice': 2385,
 'retail sales': 2359,
 'not given': 2305,
 'hr': 1133,
 'admin': 928,
 'accounts': 882,
 'senior management': 880,
 'other': 865,
 'corporate sales': 704,
 'production': 643,
 'system design': 507,
 'marketing': 487,
 'medical professional': 438,
 'creative': 396,
 'engineering design': 368,
 'finance': 339,
 'teachers': 329,
 'project management': 311,
 'university level': 305,
 'back office': 294,
 'institutional sales': 285,
 'operations': 264,
 'site engineering': 250,
 'retail': 248,
 'channel sales': 245,
 'analytics & bi': 215,
 'r&d': 208,
 'content development': 206,
 'purchase': 169,
 'Other': 160,
 'food & beverage': 146,
 'sales support': 142,
 'administration': 142,
 'logistics': 138,
 'advertising': 129,
 'online': 121,
 'corporate planning': 118,
 'qa': 110,
 'ticketing': 108,
 'technical support': 95,
 'life insurance': 85,
 'quality': 63,
 'architectural services': 62,
 'corporate banking': 62,
 'it hardware': 56,
 'desig

In [233]:
df['Job Experience Required'].value_counts().to_dict()

{'2 - 5 yrs': 2002,
 '2 - 7 yrs': 1659,
 '5 - 10 yrs': 1510,
 '3 - 8 yrs': 1366,
 '1 - 3 yrs': 1189,
 '3 - 5 yrs': 1063,
 '1 - 6 yrs': 1032,
 '1 - 5 yrs': 977,
 '0 - 5 yrs': 933,
 '0 - 1 yrs': 855,
 '0 - 2 yrs': 852,
 '2 - 4 yrs': 828,
 '4 - 9 yrs': 807,
 '0 - 3 yrs': 774,
 '3 - 6 yrs': 764,
 '2 - 6 yrs': 731,
 '5 - 8 yrs': 643,
 '1 - 4 yrs': 617,
 '1 - 2 yrs': 583,
 '4 - 8 yrs': 560,
 '4 - 6 yrs': 492,
 '2 - 3 yrs': 461,
 '10 - 15 yrs': 438,
 '3 - 7 yrs': 416,
 '7 - 12 yrs': 395,
 '8 - 13 yrs': 380,
 '6 - 11 yrs': 355,
 '5 - 7 yrs': 318,
 '4 - 7 yrs': 313,
 '7 - 10 yrs': 280,
 '0 - 4 yrs': 275,
 '6 - 10 yrs': 272,
 '8 - 10 yrs': 262,
 '0 - 0 yrs': 258,
 '8 - 12 yrs': 235,
 '6 - 8 yrs': 221,
 '3 - 4 yrs': 192,
 '10 - 20 yrs': 190,
 '5 - 9 yrs': 175,
 'Not Mentioned': 173,
 '10 - 12 yrs': 167,
 '4 - 5 yrs': 155,
 '15 - 20 yrs': 116,
 '9 - 14 yrs': 116,
 '6 - 9 yrs': 107,
 ' 3 - 8 Years': 97,
 ' 2 - 5 Years': 90,
 '10 - 14 yrs': 84,
 '5 - 6 yrs': 84,
 ' 5 - 10 Years': 84,
 '12 - 15 yrs':

In [234]:
df['Job Experience Required'].fillna("Not Mentioned",inplace=True)

In [235]:
df['Job_Exp_Min']=df['Job Experience Required'].map(lambda x:x.split(' - ')[0].strip() if x not in ['Not Mentioned','30 years and above'] else "Other")

In [236]:
df['Job_Exp_Min']

0        5
1        2
2        0
3        0
4        2
        ..
29995    9
29996    1
29997    4
29998    5
29999    2
Name: Job_Exp_Min, Length: 30000, dtype: object

In [237]:
df['Job_Exp_Max']=df['Job Experience Required'].map(lambda x:x.split(' - ')[1][:2].strip() if x not in ['Not Mentioned','30 years and above'] and '-' in x else "Other")

In [238]:
df['Job_Exp_Max']

0        10
1         5
2         1
3         5
4         5
         ..
29995    12
29996     5
29997     6
29998    10
29999     7
Name: Job_Exp_Max, Length: 30000, dtype: object

In [239]:
df['Industry'].fillna("Not Given",inplace=True)

In [240]:
df['Industry']=df['Industry'].map(lambda x:x.split(',')[0].lower().strip())

In [241]:
df['Industry']=df['Industry'].map(lambda x:x.split(' / ')[0].lower().strip() if ' / ' in x else x )

In [242]:
industry_dict=df['Industry'].value_counts().to_dict()

In [243]:
industry_dict={k:v for k,v in industry_dict.items() if v>=3}

In [244]:
industry_keys=industry_dict.keys()

In [245]:
df['Industry']=df['Industry'].map(lambda x:x if x in industry_keys else "other")

In [246]:
df.head(10)

Uniq Id            Crawl Timestamp  \
0  9be62c49a0b7ebe982a4af1edaa7bc5f  2019-07-05 01:46:07 +0000   
1  3c52d436e39f596b22519da2612f6a56  2019-07-06 08:04:50 +0000   
2  ffad8a2396c60be2bf6d0e2ff47c58d4  2019-08-05 15:50:44 +0000   
3  7b921f51b5c2fb862b4a5f7a54c37f75  2019-08-05 15:31:56 +0000   
4  2d8b7d44e138a54d5dc841163138de50  2019-07-05 02:48:29 +0000   
5  c9628ea8d9cfd2ca72e14d53783aca90  2019-08-05 03:59:27 +0000   
6  2008eb365fa0ebcb1ccd9a50efc3da49  2019-07-06 09:20:22 +0000   
7  9642bed00e26183e41ab73778bf48108  2019-08-04 03:31:17 +0000   
8  2633768efe8c6f72d75158f1c173f893  2019-07-06 15:41:47 +0000   
9  138a9ab97a766d8048f5b246172f65ed  2019-07-04 12:37:52 +0000   

                                           Job Title  \
0                              digital media planner   
1                           online bidding executive   
2  trainee research/ research executive- hi- tech...   
3                                  technical support   
4                  software test engineer -hyderabad   
5             opening for adobe analytics specialist   
6     sales- fresher-for leading property consultant   
7  opportunity for azure devops architect for hyd...   
8                                          bde- pune   
9                 technical support/ product support   

                     Job Salary Job Experience Required  \
0   Not Disclosed by Recruiter               5 - 10 yrs   
1   Not Disclosed by Recruiter                2 - 5 yrs   
2   Not Disclosed by Recruiter                0 - 1 yrs   
3      2,00,000 - 4,00,000 PA.                0 - 5 yrs   
4   Not Disclosed by Recruiter                2 - 5 yrs   
5     7,00,000 - 17,00,000 PA.                5 - 7 yrs   
6      2,00,000 - 3,00,000 PA.                0 - 0 yrs   
7   Not Disclosed by Recruiter               9 - 14 yrs   
8   Not Disclosed by Recruiter                2 - 7 yrs   
9   Not Disclosed by Recruiter                1 - 5 yrs   

                                          Key Skills         Role Category  \
0                      Media Planning| Digital Media           advertising   
1   pre sales| closing| software knowledge| clien...          retail sales   
2   Computer science| Fabrication| Quality check|...                   r&d   
3                                  Technical Support                 admin   
4   manual testing| test engineering| test cases|...  programming & design   
5   adobe experience manager| digital| digital ma...  programming & design   
6   channel partners| real estate| negotiation| p...          retail sales   
7   TFS| Azure| Git| VSTS| Docker| DynaTrace| Spl...  programming & design   
8                                                Bde   institutional sales   
9   technical support| support services| applicat...                 voice   

    Location                                    Functional Area     Industry  \
0     Mumbai  Marketing , Advertising , MR , PR , Media Plan...  advertising   
1  Pune,Pune              Sales , Retail , Business Development  it-software   
2    Gurgaon                           Engineering Design , R&D  recruitment   
3     Mumbai  IT Software - Application Programming , Mainte...  it-software   
4  Hyderabad                         IT Software - QA & Testing  it-software   
5       Pune  IT Software - Application Programming , Mainte...  it-software   
6  Bengaluru              Sales , Retail , Business Development  real estate   
7  Hyderabad  IT Software - Application Programming , Mainte...  it-software   
8       Pune              Sales , Retail , Business Development  it-software   
9  Bengaluru  ITES , BPO , KPO , LPO , Customer Service , Op...  it-software   

                                      Role                   Skill_1  \
0         Media Planning Executive/Manager            media planning   
1                  Sales Executive/Officer                 pre sales   
2                            R&D Executive          computer science   
3     

In [247]:
df['Location']=df['Location'].fillna("Not Given").map(lambda x:x.lower().strip())

In [248]:
df['Location'].value_counts().to_dict()

{'bengaluru': 5215,
 'mumbai': 3393,
 'pune': 2512,
 'hyderabad': 2281,
 'gurgaon': 1787,
 'chennai': 1613,
 'kolkata': 1361,
 'delhi': 1223,
 'noida': 1180,
 'ahmedabad': 1040,
 'delhi ncr': 768,
 'not given': 577,
 'chandigarh': 310,
 'navi mumbai': 172,
 'delhi ncr,gurgaon': 141,
 'faridabad': 121,
 'delhi ncr,gurgaon,noida': 113,
 'mumbai,mumbai suburbs': 93,
 'ghaziabad': 84,
 'mumbai,mumbai suburbs,navi mumbai': 82,
 'bengaluru,hyderabad': 78,
 'mumbai,pune': 77,
 'delhi ncr,noida': 74,
 'mumbai,mumbai': 70,
 'greater noida': 68,
 'bengaluru,chennai': 65,
 'mumbai,navi mumbai': 64,
 'thane': 62,
 'gurgaon,haryana': 59,
 'mumbai suburbs': 58,
 'bengaluru,chennai,hyderabad': 47,
 'gurgaon,noida': 46,
 'delhi ncr,delhi': 46,
 'gurgaon,delhi': 44,
 'bengaluru,bengaluru / bangalore': 44,
 'delhi,gurgaon': 44,
 'mumbai,bengaluru': 41,
 'chennai,chennai': 39,
 'mumbai,navi mumbai,thane': 38,
 'bengaluru,pune': 37,
 'delhi ncr,mumbai,bengaluru': 34,
 'mumbai,thane': 34,
 'delhi,delhi': 3

### Recommendation Logic

In [249]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [250]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Job Title', 'Job Salary',
       'Job Experience Required', 'Key Skills', 'Role Category', 'Location',
       'Functional Area', 'Industry', 'Role', 'Skill_1', 'Skill_2', 'Skill_3',
       'Job_Exp_Min', 'Job_Exp_Max'],
      dtype='object')

In [251]:
def combined_features(row):
    return row['Role Category']+" "+row['Location']+" "+row['Industry']+" "+row['Skill_1']+" "+row['Skill_2']+" "+row['Skill_3']

df["combined_features"] = df.apply(combined_features, axis =1)

In [252]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [253]:
cosine_sim = cosine_similarity(count_matrix)


In [263]:
job_searched = "python"
def get_index_from_title(title):
    return df[df["Skill_1"] == title].index.values[0]
job_index = get_index_from_title(job_searched)

In [264]:
job_index

156

In [265]:
similar_jobs = list(enumerate(cosine_sim[job_index]))
sorted_similar_jobs = sorted(similar_jobs, key=lambda x:x[1], reverse=True)

In [266]:
def get_title_from_index(index):
    return df[df.index == index]["Skill_1"].values[0]
i=0
for job in sorted_similar_jobs:
    print(get_title_from_index(job[0]))
    i=i+1
    if i>5:
        break

python
analyst
android
python
Not Given
Not Given


In [258]:
df[df['Job Title']=='python developer'].head()

Uniq Id            Crawl Timestamp  \
156   694fa3ab36d8ac71cb7d9f518aff1df0  2019-08-06 02:44:20 +0000   
217   2ed64715e1d1fd3bd0d8e6bc32327bf2  2019-08-05 09:33:26 +0000   
1057  dcff7afd271a2de8eee3718dd3a83c30  2019-08-05 09:21:15 +0000   
1568  2604e11d4ae863951b1a567ded2fa356  2019-07-06 15:54:17 +0000   
1706  1367178f55f56a3d306c78e3a9fd3702  2019-08-04 22:30:04 +0000   

             Job Title                    Job Salary Job Experience Required  \
156   python developer   Not Disclosed by Recruiter                1 - 3 yrs   
217   python developer   Not Disclosed by Recruiter                0 - 1 yrs   
1057  python developer   Not Disclosed by Recruiter                1 - 5 yrs   
1568  python developer      4,00,000 - 8,00,000 PA.                2 - 6 yrs   
1706  python developer   Not Disclosed by Recruiter                0 - 3 yrs   

                                             Key Skills         Role Category  \
156                                              Python  programming & design   
217    Debugging| Troubleshooting| Python| Interpers...  programming & design   
1057   SQL| Javascript| Python| rest| development| g...  programming & design   
1568                                          Not given  programming & design   
1706               Data Science| Data Analytics| Python  programming & design   

       Location                                    Functional Area  \
156     chennai  IT Software - Application Programming , Mainte...   
217     gurgaon  IT Software - Application Programming , Mainte...   
1057  hyderabad  IT Software - Application Programming , Mainte...   
1568  bengaluru  IT Software - Application Programming , Mainte...   
1706  hyderabad  IT Software - Application Programming , Mainte...   

         Industry                Role       Skill_1          Skill_2  \
156   recruitment  Software Developer        python        Not Given   
217   it-software  Software Developer     debugging  troubleshooting   
1057  it-software  Software Developer           sql       javascript   
1568  it-software  Software Developer     Not Given        Not Given   
1706  it-software  Software Developer  data science   data analytics   

        Skill_3 Job_Exp_Min Job_Exp_Max  \
156   Not Given           1           3   
217      python           0           1   
1057     python           1           5   
1568  Not Given           2           6   
1706     python           0           3   

                                      combined_features  
156   programming & design chennai recruitment pytho...  
217   programming & design gurgaon it-software debug...  
1057  programming & design hyderabad it-software sql...  
1568  programming & design bengaluru it-software Not...  
1706  programming & design hyderabad it-software dat...